### ISSUE TITLE
The inverse of Holidays

### ISSUE THREAD

**Issue by thomashs-zz** [Intrepidd/working_hours#11]
Let's say you configured that your work_hours that on sunday's you are always closed. It would be nice to to inform that an specific date, like november 9th from 09:00 to 12:00 it's an open period. Just like Holidays but "inverse".

**Comment by Intrepidd** [comment]
Hello, there is no bandwidth at the moment for developing new features entirely, at least on my end. 

If someone has a PR or at least a draft to get going it could speed things up indeed

**Comment by Mahmo0odsalah** [comment]
Is this still needed? I can take a shot at it if so

**Comment by Intrepidd** [comment]
Closing as stale, although don't hesitate to open a PR
