### ISSUE TITLE
Is not compatible with JRuby 1.7.9

### ISSUE THREAD

**Issue by katiam** [Intrepidd/working_hours#20]
working_hours-1.1.0/lib/working_hours/computation.rb:7: syntax error, unexpected tLABEL
    def add_days origin, days, config: nil
                                                       
                                   ^

**Comment by Intrepidd** [comment]
Are you using Jruby 2.0 compatibility mode ? ( ``JRUBY_OPTS=--2.0`` )

**Comment by katiam** [comment]
No, thanks you :)
