### ISSUE TITLE
Find windows in working time...

### ISSUE THREAD

**Issue by james2m** [Intrepidd/working_hours#24]
I need to find contiguous time slots within working our over a period of time. I'm putting together a pull request for it, but wanted your opinion on the proposed syntax.

To find all the contiguous 2 hour slots from Time.utc(2014, 8, 4, 8, 30) until Time.utc(2014, 8, 11) I was thinking of this;

```ruby
WorkingHours::Duration.new(2, :hours).between(Time.utc(2014, 8, 4, 8, 30), Time.utc(2014, 8, 11))
```

Returning an array. See any problems with this, or a preferred syntax?

**Comment by Intrepidd** [comment]
This seems like a very specific problem to me, not sure it should be in the gem.

Thoughts @jarthod  ?

**Comment by james2m** [comment]
I'll do it outside. That's why I asked before sending the pull request.

**Comment by jarthod** [comment]
Yeah that's definitely too specific IMO too.
