### ISSUE TITLE
Thread Safety

### ISSUE THREAD

**Issue by taylorbrooks** [Intrepidd/working_hours#29]
I know the docs say this gem is thread-safe, but I just want to make sure...

If I'm using `working_hours` in Sidekiq and I'm using different configs would it still be thread-safe?

I would expect to pass the config into functions, instead of maintaining state in an initializer... maybe that's what the block is for?

**Comment by Intrepidd** [comment]
Each thread has [its own config](https://github.com/Intrepidd/working_hours/blob/master/lib/working_hours/config.rb#L92) but it can be shared.

If you want to use different configs in different workers then yes, you have to use [with_config](https://github.com/Intrepidd/working_hours/blob/master/lib/working_hours/config.rb#L75) the config will be applied only inside the block and not impact other threads.

**Comment by taylorbrooks** [comment]
Awesome, thanks!
