### ISSUE TITLE
about working day

### ISSUE THREAD

**Issue by CooperFu** [Intrepidd/working_hours#30]
hey there.
I am a chinese developer and our team are using your gem . thanks your guys make this!

and now we found a problem about `working day`. the config is only can set working day to holidays . but can not set holidays to working days. chinese holidays is really complicated. so can you guys can add this feature? thanks a lot!

**Comment by dmitry** [comment]
@naotou isn't `WorkingHours::Config.holidays` matches what you are searching for?

**Comment by jarthod** [comment]
It is not, If I understood correctly, @naotou wants a way to mark some regular **non-working** days (like sundays) as working, so the opposite of what `WorkingHours::Config.holidays` does.

**Comment by naotou** [comment]
yeah @jarthod is right! sorry about my english....

**Comment by tom-lord** [comment]
Duplicates https://github.com/Intrepidd/working_hours/issues/11
