### ISSUE TITLE
Go back to opening time

### ISSUE THREAD

**Issue by dankimio** [Intrepidd/working_hours#31]
For example, on Monday at 10:00, the closest opening time is 9:00. Is there a quick way to go back to that opening time? If not, I could submit a PR (if that feature is relevant).

**Comment by dankimio** [comment]
Just noticed #25. I'll try to fix that and submit a pull request.

**Comment by jarthod** [comment]
Yes, please do :+1:

**Comment by jarthod** [comment]
Closing as duplicate of #25
