### ISSUE TITLE
WorkingHours.in_working_hours?(Time.zone.now) not working on heroku ?

### ISSUE THREAD

**Issue by vkeziah** [Intrepidd/working_hours#34]
set time zone and updated code base accordingly on heroku , but the above method is not working as I expected , it always returns true only even my config values are out of the range 
![cropped](https://cloud.githubusercontent.com/assets/6500069/26313439/828f5ade-3f28-11e7-96ba-f9eeddacca30.png)

**Comment by Intrepidd** [comment]
Hey,

your `Time.zone.now.in_working_hours?` seems to be outside of the `with_config` block
