### ISSUE TITLE
This is more like a question for dynamic entering

### ISSUE THREAD

**Issue by jofix17** [Intrepidd/working_hours#41]
Would it be possible for the days to be dynamic? I'm gonna make the admin the setter for the dates working hours and holidays. Here is a snippet of my code: inside config/initializers/working_hours.rb

`
# Configure working hours
WorkingHours::Config.working_hours = {
  sun: { '22:00' => '24:00', '00:00' => '06:00' },
  mon: { '22:00' => '24:00', '00:00' => '06:00' },
  tue: { '22:00' => '24:00', '00:00' => '06:00' },
  wed: { '22:00' => '24:00', '00:00' => '06:00' },
  thu: { '22:00' => '24:00', '00:00' => '06:00' },
  fri: { '22:00' => '24:00', '00:00' => '06:00' },
  sat: { '22:00' => '24:00', '00:00' => '06:00' }
}

# Configure timezone (uses activesupport, defaults to UTC)
WorkingHours::Config.time_zone = 'Asia/Manila'

# Configure holidays
arr_of_dates = []
holidates = [{ day: 10, month: 11, year: 2020 },
             { day: 24, month: 12, year: 2020 },
             { day: 25, month: 12, year: 2020 },
             { day: 30, month: 12, year: 2020 },
             { day: 31, month: 12, year: 2020 }]

holidates.each do |d|
  arr_of_dates << Date.new(d[:year], d[:month], d[:day])
end

WorkingHours::Config.holidays = arr_of_dates
`

Thanks in advance

**Comment by Intrepidd** [comment]
Have you looked at the `with_config` method? 

```ruby
WorkingHours::Config.with_config(working_hours: {mon:{'09:00' => '18:00'}}, holidays: [], time_zone: 'Paris') do
  # Intense calculations
end
```

You should be able to store your config in a database and wrap your code with this to use the latest available config, in an `around_action` for example of you're using rails.

**Comment by jofix17** [comment]
Thanks a bunch
