### ISSUE TITLE
Inconsistency with business_time gem

### ISSUE THREAD

**Issue by sarons** [Intrepidd/working_hours#50]
I'm trying to migrate from business_time gem to working_hours gem, but testing gives inconsistent results between the 2 gems. 
```
Time.utc(2014, 8, 4, 8, 32) + 4.working.hours
=> Mon, 04 Aug 2014 13:00:00.000000000 UTC +00:00
4.business_hours.after(Time.utc(2014, 8, 4, 8, 32))
=> 2014-08-04 12:32:00 UTC

Time.now + 20.working.hours
=> Thu, 25 Jan 2024 15:33:24.000000000 UTC +00:00
20.business_hours.after(Time.now)
=> 2024-01-24 07:33:13.448023076 +0000
```

Am I doing something wrong here?
Has anyone done such migration?

Since business_time https://github.com/bokmann/business_time was mentioned in the documentation, I assumed it would be a straight forward migration.
I'm kinda stuck, any help would be greatly appreciated.
Thanks

**Comment by Intrepidd** [comment]
This probably has to do with the default config (which is 09 -> 17 on weekdays)

Regarding your first example : `Time.utc(2014, 8, 4, 8, 32)` is outside of working hours, so the count start at the next working hour slot (09:00), add 4 hours to that and you end up with the result.

I don't know the exact way `business_time` works but it's possible the default config is different, explaining your inconsistencies

**Comment by sarons** [comment]
Thanks for the quick reply, I'll look into it

**Comment by sarons** [comment]
@Intrepidd you were right, it works when I configure it similar to old `business_time` config.
Thanks!
